# Generated by Django 4.1.4 on 2022-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
