# Generated by Django 4.1.4 on 2022-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.CharField(default='https://parallel.cymru/wp-content/uploads/Generic-Book-Placeholder-icon-300x300.png', max_length=500),
        ),
    ]
